# Generated by Django 5.2.1 on 2025-05-23 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
            ],
        ),
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('reponsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambientes')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=40)),
                ('prioridade', models.CharField(max_length=20)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambientes')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutentor', to='app.funcionarios')),
                ('manutentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestor', to='app.funcionarios')),
                ('requisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quem_requisitou', to='app.funcionarios')),
                ('patrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patrimonios')),
            ],
        ),
    ]
