# Generated by Django 5.2 on 2025-04-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.IntegerField(unique=True)),
                ('sn', models.CharField(max_length=20, unique=True)),
                ('reponsavel', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gestores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('Cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manutentores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
                ('destor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gestores')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=40)),
                ('prioridade', models.CharField(max_length=20)),
                ('funcionario', models.CharField(max_length=40)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambientes')),
                ('manutentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manutentores')),
                ('patrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patrimonios')),
            ],
        ),
    ]
