# Generated by Django 5.2.1 on 2025-05-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambientes',
            old_name='reponsavel',
            new_name='responsavel',
        ),
    ]
