# Generated by Django 5.2.1 on 2025-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_reponsavel_ambientes_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='titulo',
            field=models.CharField(default='sem titulo', max_length=50),
            preserve_default=False,
        ),
    ]
